version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo test
  build:
    commands:
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - export PATH=$PWD/:$PATH
      - yum -y install jq
      - aws eks update-kubeconfig --region us-west-1 --name test --role-arn arn:aws:iam::123456789:role/EksCodeBuildkubectlRole
      - kubectl get nodes